# ========================================
#              DATABASE
# ========================================
spring.datasource.url=jdbc:postgresql://user-db:5432/User
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

# ========================================
#           EUREKA DISCOVERY
# ========================================
eureka.client.service-url.defaultZone=http://eureka-server-1:8761/eureka/,http://eureka-server-2:8762/eureka/