spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.datasource.url=jdbc:postgresql://db:5432/Books
spring.datasource.username=postgres
spring.datasource.password=postgres
notification.service.url=http://notification-service:8081

logging.level.org.hibernate.SQL=DEBUG
spring.jpa.hibernate.ddl-auto=update