spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.datasource.url=jdbc:postgresql://localhost:5432/Books
spring.datasource.username=postgres
spring.datasource.password=postgres

logging.level.org.hibernate.SQL=DEBUG
spring.jpa.hibernate.ddl-auto=update