# ========================================
#           EUREKA DISCOVERY
# ========================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# ========================================
#               LOGGING
# ========================================
logging.level.com.netflix.eureka=DEBUG
logging.level.com.netflix.discovery=DEBUG